// Generated by CoffeeScript 1.9.3
var SEEN, _, handleError, handleGoodLoans, loanSeen, makeRequest, pushLoan, pusher, reqwest;

require('dotenv').load();

reqwest = require('reqwest');

pusher = new (require('pushbullet'))(process.env.PUSHBULLET_KEY);

_ = require('lodash');

SEEN = [];

handleError = function(err) {
  console.log('Error!', err.statusText + " -- " + err.responseText);
  return pusher.note(process.env.PUSHBULLET_ACCOUNT, 'Error!', err.statusText + " -- " + err.responseText);
};

loanSeen = function(loan) {
  return _.contains(SEEN, loan.id);
};

pushLoan = function(loan) {
  var url;
  SEEN.push(loan.id);
  url = "https://www.lendingclub.com/browse/loanDetail.action?loan_id=" + loan.id;
  console.log('Description Found!', url);
  return pusher.link(process.env.PUSHBULLET_ACCOUNT, 'Description Found!', url);
};

handleGoodLoans = function(arg) {
  var loans;
  loans = arg.loans;
  return _(loans).reject({
    desc: null
  }).reject(loanSeen).each(pushLoan).run();
};

makeRequest = function() {
  console.log((new Date) + ": Checking...");
  return reqwest({
    url: 'https://api.lendingclub.com/api/investor/v1/loans/listing',
    method: 'get',
    type: 'json',
    headers: {
      Authorization: process.env.LENDINGCLUB_KEY
    },
    data: {
      showAll: true
    },
    success: handleGoodLoans,
    error: handleError
  });
};

console.log('Starting...');

setInterval(makeRequest, 1000 * 60 * 10);

makeRequest();
